Add ARM64 Build of Docker Image
yiisoft/yii-docker pull request #31
Opened 2023-03-29 22:22 UTC by mabentley85

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | Adds AMR64 build of the docker image

2023-03-31 07:47 UTC, schmunk42 commented
The build itself is nice, but I think we need a way to trigger it just on a weekly basis and/or manually, just because the build runs over an hour - I think we don't want that for every commit :)

2023-03-31 18:02 UTC, mabentley85 commented
@schmunk42 Agreed, these jobs take way too long.

Running them only when manually triggered or once a week could be accomplished by updating the `on` section to look like this:
```
on:
  schedule:    
    - cron: '0 6 * * 1'
```
Building the master branch on Mondays at 6AM (for example). Though the pushing to docker hub would only occur when the current revision has been tagged.

What do you think of that?

2023-04-06 08:27 UTC, schmunk42 commented
@mabentley85 Sounds great.

We already have a weekly schedule for this images.

Maybe some jobs can only run `if: schedule,manual,[extended build branch]` (pseudo-code) or we create another github-workflow with only `schedule`. I haven't tried this yet, so feel free with the implementation.

2023-04-10 08:08 UTC, schmunk42 requested changes

2023-04-10 08:08 UTC, schmunk42 commented on .github/workflows/docker-image.yml
> -  push:
You removed `push` and `PR`, but we need them.
Maybe it's better to create two separate workflows (.yml) files.

One like the existing for `push` and `pull_request` the other for `dispatch` and `schedule` with ARM builds.

2023-04-10 18:12 UTC, mabentley85 commented
@schmunk42 Closing this Pull Request as the solution provided by @albertborsos in #33 is better.

2023-04-10 18:12 UTC, closed without merging