Replaced php image
yiisoft/yii-docker pull request #6
Opened 2020-02-08 19:50 UTC by Fantom409

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #5

2020-02-08 20:41 UTC, schmunk42 requested changes

2020-02-08 20:41 UTC, schmunk42 commented on php/Dockerfile-debian
> +FROM yiisoftware/yii-php:${PHP_BASE_IMAGE_VERSION}
This repo is for building `yiisoftware/yii-php`, this should be reverted.

Rest is fine.

2020-02-17 20:42 UTC, samdark commented
@schmunk42 I've adjusted `FROM`. Is it OK now? Ready to be merged?

2020-02-17 22:13 UTC, merged

2020-02-17 22:13 UTC, schmunk42 commented
Thank you!